services:
  tmt:
    container_name: task_management_tool
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./db/:/TaskManagementTool/db/"
    ports:
      - "8000:8000"
    command: uv run fastapi run tmt/main.py --host 0.0.0.0 --port 8000

  tests:
    build:
      context: .
    command: uv run pytest tests
    profiles:
      - tests